# Generated by Django 4.0.6 on 2022-07-24 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='ordercartmapper',
            table='order_cart_mapper',
        ),
    ]
