# Generated by Django 4.0.6 on 2022-07-29 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0008_alter_cartitem_cart'),
        ('order', '0003_order_address_order_cart_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cart.cart'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('user', 'cart')},
        ),
    ]
