# Generated by Django 4.0.6 on 2022-07-25 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartitem',
            table='cart_item',
        ),
    ]
